version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: youtube-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: YouTube
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: